export const COUNTRY_CODES = [
  { code: "+91", country: "India", flag: "🇮🇳", short: "IN" },
  { code: "+1", country: "United States", flag: "🇺🇸", short: "US" },
  { code: "+1", country: "Canada", flag: "🇨🇦", short: "CA" },
  { code: "+44", country: "United Kingdom", flag: "🇬🇧", short: "GB" },
  { code: "+971", country: "UAE", flag: "🇦🇪", short: "AE" },
  { code: "+966", country: "Saudi Arabia", flag: "🇸🇦", short: "SA" },
  { code: "+65", country: "Singapore", flag: "🇸🇬", short: "SG" },
  { code: "+61", country: "Australia", flag: "🇦🇺", short: "AU" },
  { code: "+49", country: "Germany", flag: "🇩🇪", short: "DE" },
  { code: "+33", country: "France", flag: "🇫🇷", short: "FR" },
  { code: "+81", country: "Japan", flag: "🇯🇵", short: "JP" },
  { code: "+86", country: "China", flag: "🇨🇳", short: "CN" },
  { code: "+82", country: "South Korea", flag: "🇰🇷", short: "KR" },
  { code: "+60", country: "Malaysia", flag: "🇲🇾", short: "MY" },
  { code: "+977", country: "Nepal", flag: "🇳🇵", short: "NP" },
  { code: "+94", country: "Sri Lanka", flag: "🇱🇰", short: "LK" },
  { code: "+880", country: "Bangladesh", flag: "🇧🇩", short: "BD" },
  { code: "+92", country: "Pakistan", flag: "🇵🇰", short: "PK" },
  { code: "+27", country: "South Africa", flag: "🇿🇦", short: "ZA" },
  { code: "+234", country: "Nigeria", flag: "🇳🇬", short: "NG" },
] as const;
