import type { Listing } from "@/lib/supabase/types";

// Generated property images
const IMAGES = {
  mumbai_apt: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141236_a02515f3-db0c-4a5f-b68a-74f834f7d43d.png",
  bangalore_interior: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141240_5b42b289-a057-4b70-a9ee-3c504e8abe06.png",
  hyderabad_villa: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141244_9d5670ca-f6ab-41bf-ade8-f14d3d3f44eb.png",
  whitefield_plot: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141247_ca666b57-d53c-47da-bd5d-acb8c9c2b208.png",
  delhi_restaurant: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141301_bf88f1bf-8591-401e-bfb2-9b3dd1b7f40d.png",
  powai_pg: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141305_daf71c2f-ca32-4840-afb8-8bd0bdd3a66f.png",
  bkc_office: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141308_e0d49c93-9986-4f19-ba68-35d675ce7d52.png",
  karjat_farm: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141312_8600489a-367c-4d2c-9a89-72b2e3941cd7.png",
};

export const CITY_IMAGES = {
  Mumbai: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141323_a499a461-e3f0-42d2-a86f-95f9c724320b.png",
  Delhi: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141327_a8f0cd4f-d3c2-49fa-a36f-8ef0a7678418.png",
  Bangalore: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141330_07d6388c-058d-47a7-90d3-503eed1c6abf.png",
  Hyderabad: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141334_1853bb78-95e8-44b0-bc3c-82b79b249b35.png",
  Chennai: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141343_1110e6d8-904d-4415-aac3-c510edec333f.png",
  Pune: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141347_81d56da0-05fd-46e0-84d2-8860db682f24.png",
  Kolkata: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141350_541ebde0-2ce3-4970-b87e-8344861c855e.png",
  Ahmedabad: "https://d8j0ntlcm91z4.cloudfront.net/user_38VX9YcU2aOrdXv5WCsBGD7ZVVt/hf_20260507_141354_98a0b381-227d-4ad4-b39c-ac22d96b44b1.png",
};

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    user_id: "u1",
    status: "active",
    listing_type: "sale",
    property_type: "apartment",
    title: "3 BHK Luxury Apartment in Bandra West",
    description: "Stunning sea-facing apartment with modern amenities, modular kitchen, and premium fittings. Located in a prime Bandra West society with 24/7 security, swimming pool, and gym.",
    price: 35000000,
    price_negotiable: true,
    rent_deposit: null,
    maintenance_monthly: 15000,
    address: "Bandra West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400050",
    locality: "Bandra West",
    latitude: 19.0596,
    longitude: 72.8295,
    bedrooms: 3,
    bathrooms: 3,
    area_sqft: 1850,
    carpet_area_sqft: 1450,
    floor_number: 14,
    total_floors: 22,
    facing: "West",
    age_years: 2,
    furnishing: "semi_furnished",
    parking: "covered",
    amenities: ["Gym", "Swimming Pool", "Security", "Lift", "Power Backup", "Club House", "Garden"],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u1", role: "builder", full_name: "Lodha Group", phone: "9876543210", email: "info@lodha.com", avatar_url: null, is_verified: true, company_name: "Lodha Group", rera_number: "P51800001234", created_at: "" },
    media: [
      { id: "m1", listing_id: "1", type: "photo", url: IMAGES.mumbai_apt, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "2",
    user_id: "u2",
    status: "active",
    listing_type: "rent",
    property_type: "apartment",
    title: "2 BHK Furnished Flat near Koramangala",
    description: "Fully furnished 2BHK apartment ideal for IT professionals. Close to Koramangala 4th Block, near restaurants and metro station.",
    price: 45000,
    price_negotiable: false,
    rent_deposit: 100000,
    maintenance_monthly: 5000,
    address: "HSR Layout",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560102",
    locality: "HSR Layout",
    latitude: 12.9116,
    longitude: 77.6474,
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1100,
    carpet_area_sqft: 900,
    floor_number: 5,
    total_floors: 12,
    facing: "East",
    age_years: 5,
    furnishing: "fully_furnished",
    parking: "covered",
    amenities: ["Gym", "Security", "Lift", "Power Backup", "CCTV"],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u2", role: "individual", full_name: "Priya Sharma", phone: "9876543211", email: "priya@email.com", avatar_url: null, is_verified: false, company_name: null, rera_number: null, created_at: "" },
    media: [
      { id: "m2", listing_id: "2", type: "photo", url: IMAGES.bangalore_interior, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "3",
    user_id: "u3",
    status: "active",
    listing_type: "sale",
    property_type: "villa",
    title: "4 BHK Independent Villa in Jubilee Hills",
    description: "Spacious independent villa with private garden, car parking for 3 vehicles, and servant quarters. Premium location in Jubilee Hills.",
    price: 85000000,
    price_negotiable: true,
    rent_deposit: null,
    maintenance_monthly: null,
    address: "Road No. 36, Jubilee Hills",
    city: "Hyderabad",
    state: "Telangana",
    pincode: "500033",
    locality: "Jubilee Hills",
    latitude: 17.4319,
    longitude: 78.4074,
    bedrooms: 4,
    bathrooms: 5,
    area_sqft: 4200,
    carpet_area_sqft: 3800,
    floor_number: null,
    total_floors: 2,
    facing: "North",
    age_years: 8,
    furnishing: "semi_furnished",
    parking: "both",
    amenities: ["Garden", "Security", "Power Backup", "Water Supply", "CCTV"],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u3", role: "agent", full_name: "Rahul Properties", phone: "9876543212", email: "rahul@props.com", avatar_url: null, is_verified: true, company_name: "Rahul Properties", rera_number: "A51800005678", created_at: "" },
    media: [
      { id: "m3", listing_id: "3", type: "photo", url: IMAGES.hyderabad_villa, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "4",
    user_id: "u4",
    status: "active",
    listing_type: "sale",
    property_type: "plot",
    title: "1200 sq.ft Residential Plot in Whitefield",
    description: "BBMP approved residential plot in a gated community. Corner plot with clear title and all documents in order. Ready for construction.",
    price: 9600000,
    price_negotiable: true,
    rent_deposit: null,
    maintenance_monthly: null,
    address: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560066",
    locality: "Whitefield",
    latitude: 12.9698,
    longitude: 77.7500,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 1200,
    carpet_area_sqft: null,
    floor_number: null,
    total_floors: null,
    facing: "East",
    age_years: null,
    furnishing: null,
    parking: null,
    amenities: [],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u4", role: "individual", full_name: "Venkat Reddy", phone: "9876543213", email: "venkat@email.com", avatar_url: null, is_verified: false, company_name: null, rera_number: null, created_at: "" },
    media: [
      { id: "m4", listing_id: "4", type: "photo", url: IMAGES.whitefield_plot, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "5",
    user_id: "u5",
    status: "active",
    listing_type: "sale",
    property_type: "business",
    title: "Profitable Restaurant for Sale in Connaught Place",
    description: "Well-established fine dining restaurant with 80 seating capacity. Prime CP location with excellent footfall. All licenses current.",
    price: 25000000,
    price_negotiable: true,
    rent_deposit: null,
    maintenance_monthly: null,
    address: "Block A, Connaught Place",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    locality: "Connaught Place",
    latitude: 28.6315,
    longitude: 77.2167,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 2800,
    carpet_area_sqft: 2400,
    floor_number: 0,
    total_floors: 2,
    facing: null,
    age_years: 12,
    furnishing: "fully_furnished",
    parking: null,
    amenities: [],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u5", role: "business_owner", full_name: "Amit Kapoor", phone: "9876543214", email: "amit@restaurant.com", avatar_url: null, is_verified: true, company_name: null, rera_number: null, created_at: "" },
    media: [
      { id: "m5", listing_id: "5", type: "photo", url: IMAGES.delhi_restaurant, display_order: 0, is_cover: true },
    ],
    business_details: {
      listing_id: "5",
      business_type: "Restaurant",
      annual_revenue: 18000000,
      employee_count: 25,
      years_in_operation: 12,
      reason_for_selling: "Relocating abroad",
      assets_included: "All kitchen equipment, furniture, POS system, brand name",
      lease_details: "15-year lease, 8 years remaining, rent 3.5L/month",
    },
  },
  {
    id: "6",
    user_id: "u6",
    status: "active",
    listing_type: "pg_coliving",
    property_type: "apartment",
    title: "Premium PG for Boys in Powai with Meals",
    description: "AC rooms, home-cooked meals, high-speed WiFi, housekeeping. Near IIT Bombay and Hiranandani Gardens.",
    price: 15000,
    price_negotiable: false,
    rent_deposit: 15000,
    maintenance_monthly: null,
    address: "Hiranandani Gardens, Powai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400076",
    locality: "Powai",
    latitude: 19.1176,
    longitude: 72.9060,
    bedrooms: 1,
    bathrooms: 1,
    area_sqft: 200,
    carpet_area_sqft: null,
    floor_number: 3,
    total_floors: 5,
    facing: null,
    age_years: null,
    furnishing: "fully_furnished",
    parking: null,
    amenities: ["Power Backup", "Water Supply", "CCTV", "Security"],
    pg_gender: "male",
    pg_meals_included: true,
    pg_occupancy: "double",
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u6", role: "individual", full_name: "Sanjay Mehta", phone: "9876543215", email: "sanjay@pg.com", avatar_url: null, is_verified: false, company_name: null, rera_number: null, created_at: "" },
    media: [
      { id: "m6", listing_id: "6", type: "photo", url: IMAGES.powai_pg, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "7",
    user_id: "u7",
    status: "active",
    listing_type: "lease",
    property_type: "commercial_office",
    title: "3000 sq.ft Office Space in BKC",
    description: "Plug-and-play furnished office space in Bandra Kurla Complex. 50 workstations, 2 cabins, conference room, pantry. Ready to move.",
    price: 250000,
    price_negotiable: true,
    rent_deposit: 750000,
    maintenance_monthly: 25000,
    address: "BKC",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400051",
    locality: "BKC",
    latitude: 19.0654,
    longitude: 72.8654,
    bedrooms: null,
    bathrooms: 2,
    area_sqft: 3000,
    carpet_area_sqft: 2600,
    floor_number: 8,
    total_floors: 15,
    facing: "South",
    age_years: 3,
    furnishing: "fully_furnished",
    parking: "covered",
    amenities: ["Lift", "Security", "Power Backup", "Fire Safety", "CCTV"],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u7", role: "agent", full_name: "NoBroker Commercial", phone: "9876543216", email: "commercial@nobroker.com", avatar_url: null, is_verified: true, company_name: "NoBroker", rera_number: null, created_at: "" },
    media: [
      { id: "m7", listing_id: "7", type: "photo", url: IMAGES.bkc_office, display_order: 0, is_cover: true },
    ],
  },
  {
    id: "8",
    user_id: "u8",
    status: "active",
    listing_type: "sale",
    property_type: "farmland",
    title: "5 Acre Farmland near Karjat with Mango Orchards",
    description: "Lush green farmland with existing mango and coconut trees. Natural water source, fenced property. Perfect for weekend farmhouse.",
    price: 12500000,
    price_negotiable: true,
    rent_deposit: null,
    maintenance_monthly: null,
    address: "Near Karjat",
    city: "Raigad",
    state: "Maharashtra",
    pincode: "410201",
    locality: "Karjat",
    latitude: 18.9106,
    longitude: 73.3231,
    bedrooms: null,
    bathrooms: null,
    area_sqft: 217800,
    carpet_area_sqft: null,
    floor_number: null,
    total_floors: null,
    facing: null,
    age_years: null,
    furnishing: null,
    parking: null,
    amenities: ["Water Supply"],
    pg_gender: null,
    pg_meals_included: null,
    pg_occupancy: null,
    auction_start: null,
    auction_end: null,
    auction_base_price: null,
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    expires_at: null,
    user: { id: "u8", role: "individual", full_name: "Deepak Patil", phone: "9876543217", email: "deepak@email.com", avatar_url: null, is_verified: false, company_name: null, rera_number: null, created_at: "" },
    media: [
      { id: "m8", listing_id: "8", type: "photo", url: IMAGES.karjat_farm, display_order: 0, is_cover: true },
    ],
  },
];
